package com.act.geomapper.ui.theme

import androidx.compose.runtime.compositionLocalOf
import com.act.geomapper.data.settings.AppLanguage

data class AppStrings(
    // Header
    val proyectos    : String,
    val capas        : String,
    val basemap      : String,
    val importar     : String,
    val exportar     : String,
    val parcelacion  : String,
    val configuracion: String,
    val campoActivo  : String,
    val menuLabel    : String,
    // Captura
    val gps          : String,
    val mapa         : String,
    val finalizar    : String,
    val cancelar     : String,
    val deshacer     : String,
    val puntoGps     : String,
    val tocaMapaGps  : String,
    val linea        : String,
    val poligono     : String,
    val punto        : String,
    val herramientaCaptura: String,
    val colapsar     : String,
    val expandir     : String,
    // Capas
    val capasTitle   : String,
    val puntos       : String,
    val lineas       : String,
    val poligonos    : String,
    val sinEntidades : String,
    val entidades    : String,
    val entidad      : String,
    val rasteres     : String,
    val eliminarTodoTitulo        : String,
    val eliminarTodoConfirmacion  : String,
    val eliminarTodoBoton         : String,
    val nombreLabel               : String,
    val propietarioLabel          : String,
    val propietarioAtributoLabel  : String,
    // Brújula
    val norte        : String,
    val sur          : String,
    val este         : String,
    val oeste        : String,
    // Proyectos
    val nuevoProyecto: String,
    val sinProyectos : String,
    val sinNombre    : String,
    val nombreProyectoLabel     : String,
    val descripcionOpcional     : String,
    val crearProyecto           : String,
    val nuevo                   : String,
    val descartar                : String,
    // Acciones
    val guardar      : String,
    val eliminar      : String,
    val editar       : String,
    val compartir    : String,
    val sinGps       : String,
    val volver       : String,
    val ok           : String,
    val confirmar    : String,
    val cerrar       : String,
    // Coordenadas
    val ingresarCoord: String,
    val ingresarCoordGms: String,
    val valoresInvalidos: String,
    val latitud      : String,
    val longitud     : String,
    val capturar     : String,
    val coordInvalidas: String,
    // Import
    val importarMapa         : String,
    val importarGeoPdf       : String,
    val importarKml          : String,
    val importarGpx          : String,
    val importarGeoJson      : String,
    val importarShapefile    : String,
    val ingresarCoordsManual : String,
    val rellenoPoligonos     : String,
    val rellenoPoligonosDesc : String,
    // Export
    val exportarDatos        : String,
    val geoJsonDesc          : String,
    val kmlDesc              : String,
    val gpxDesc              : String,
    val shpDesc              : String,
    val sinEntidadesExportar : String,
    // Parcelación
    val herramientasTerreno  : String,
    val corteManual          : String,
    val trazarVia            : String,
    val subdividirLote       : String,
    val trazarDireccionCorte : String,
    val corte                : String,
    val subdividir           : String,
    val relleno              : String,
    val borde                : String,
    val aplicarSubdivision   : String,
    val subdivision          : String,
    val frenteObjetivo       : String,
    val porArea              : String,
    val partesIguales        : String,
    val frenteM              : String,
    val areaPorParcela       : String,
    val numeroParcelas       : String,
    val sinPoligono          : String,
    val areaToggle           : String,
    val ladosToggle          : String,
    val deshacerPunto        : String,
    val anadirPunto          : String,
    val cortarDeNuevo        : String,
    val tipoPlaceholder      : String,
    val trazarEje            : String,
    val dibujarEje           : String,
    val editarParcelas       : String,
    val via                  : String,
    val seleccionarPoligono  : String,
    val sinPoligonosProyecto : String,
    val poligonoNumero       : String,
    val parcelaDefault       : String,
    // Settings
    val unidadesDistancia    : String,
    val metros               : String,
    val kilometros           : String,
    val unidadesArea         : String,
    val idiomaLabel          : String,
    val coordenadasLabel     : String,
    val formatoGms           : String,
    val temaLabel            : String,
    val oscuro               : String,
    val claro                : String,
    val mejorasComentarios   : String,
    val feedbackDescripcion  : String,
    val whatsappMensaje      : String,
    val escribirWhatsapp     : String,
    val dispositivoRootTitulo: String,
    val dispositivoRootDesc  : String,
    val entendido            : String,
    // Basemap
    val basemapSatelite      : String,
    val basemapHibrido       : String,
    val basemapCalles        : String,
    val mapaDeFondo          : String,
    val definirAreaDescarga  : String,
    // Descarga de mapa offline
    val descargarAreaDefinida: String,
    val fuenteLabel          : String,
    val nivelDetalleMax      : String,
    val zoomBarrios          : String,
    val zoomCalles           : String,
    val zoomManzanas         : String,
    val zoomEdificios        : String,
    val zoomDetalleAlto      : String,
    val zoomMaximo           : String,
    val estimadoTiles        : String,
    val areaGrandeAdvertencia: String,
    val descargadoPct        : String,
    val descargaCompletada   : String,
    val errorDescarga        : String,
    val descargarBtn         : String,
    // MapScreen
    val miUbicacion          : String,
    val continuarBtn         : String,
    val editando             : String,
    val cancelarEdicion      : String,
    val tocaMapaVertices     : String,
    val poligonoListo        : String,
    // GNSS Dialog
    val gnssExterno          : String,
    val conectadoA           : String,
    val conectando           : String,
    val errorConDetalle      : String,
    val desconectado         : String,
    val desconectar          : String,
    val sinReceptoresBt      : String,
    val seleccionaReceptor   : String,
    val dispositivoGenerico  : String,
    val actualizarLista      : String,
    val detenerGrabacion     : String,
    val grabarNmea           : String,
    val compartirArchivoLbl  : String,
    val limpiarError         : String,
    val ipReceptor           : String,
    val puertoTcp            : String,
    val conectarWifiPrimero  : String,
    val conectarBtn          : String,
    val estadoLabel          : String,
    val idleLabel            : String,
    val conectadoLabel       : String,
    val errorLabel           : String,
    val grabacionLabel       : String,
    val sinGrabacionActiva   : String,
    val archivoActualLbl     : String,
    val carpetaActivaLbl     : String,
    val rutaGuardadoLbl      : String,
    val ipHostLabel          : String,
    val puertoLabel          : String,
    val usuarioLabel         : String,
    val contrasenaLabel      : String,
    val mountpointLabel      : String,
    val configuracionCompleta: String,
    val velocidadLabel       : String,
    val recibidosLabel       : String,
)

val StringsEs = AppStrings(
    proyectos     = "Proyectos",
    capas         = "Capas",
    basemap       = "Mapa Base",
    importar      = "Importar",
    exportar      = "Exportar",
    parcelacion   = "Parcelación",
    configuracion = "Config.",
    campoActivo   = "Activo",
    menuLabel     = "Menú",
    gps           = "GPS",
    mapa          = "Mapa",
    finalizar     = "Fin",
    cancelar      = "Cancelar",
    deshacer      = "Deshacer",
    puntoGps      = "Punto GPS",
    tocaMapaGps   = "Toca el mapa o GPS",
    linea         = "Línea",
    poligono      = "Polígono",
    punto         = "Punto",
    herramientaCaptura = "HERRAMIENTA DE CAPTURA",
    colapsar      = "Colapsar",
    expandir      = "Expandir",
    capasTitle    = "Capas",
    puntos        = "Puntos",
    lineas        = "Líneas",
    poligonos     = "Polígonos",
    sinEntidades  = "Sin entidades capturadas.",
    entidades     = "entidades",
    entidad       = "entidad",
    rasteres      = "Rásteres",
    eliminarTodoTitulo       = "¿Eliminar todo?",
    eliminarTodoConfirmacion = "Se eliminarán las %d entidades. Esta acción no se puede deshacer.",
    eliminarTodoBoton        = "Eliminar todo",
    nombreLabel              = "Nombre",
    propietarioLabel         = "Propietario",
    propietarioAtributoLabel = "Propietario / Atributo",
    norte         = "N",
    sur           = "S",
    este          = "E",
    oeste         = "O",
    nuevoProyecto = "Nuevo Proyecto",
    sinProyectos  = "Sin proyectos. Toca + para crear uno.",
    sinNombre     = "Sin nombre",
    nombreProyectoLabel = "Nombre del proyecto",
    descripcionOpcional = "Descripción (opcional)",
    crearProyecto        = "Crear proyecto",
    nuevo                = "Nuevo",
    descartar            = "Descartar",
    guardar       = "Guardar",
    eliminar      = "Eliminar",
    editar        = "Editar",
    compartir     = "Compartir",
    sinGps        = "Sin GPS",
    volver        = "Volver",
    ok            = "OK",
    confirmar     = "Confirmar",
    cerrar        = "Cerrar",
    ingresarCoord = "Ingresar coordenadas",
    ingresarCoordGms = "Ingresar coordenadas GMS",
    valoresInvalidos = "Valores inválidos",
    latitud       = "Latitud",
    longitud      = "Longitud",
    capturar      = "Capturar",
    coordInvalidas= "Coordenadas inválidas",
    importarMapa         = "Importar mapa",
    importarGeoPdf       = "Importar GeoPDF / TIFF",
    importarKml          = "Importar KML",
    importarGpx          = "Importar GPX",
    importarGeoJson      = "Importar GeoJSON",
    importarShapefile    = "Importar Shapefile ZIP",
    ingresarCoordsManual = "Ingresar coordenadas manualmente",
    rellenoPoligonos     = "Relleno de polígonos",
    rellenoPoligonosDesc = "Ver polígonos con fondo translúcido.",
    exportarDatos        = "Exportar datos",
    geoJsonDesc          = "Recomendado: conserva geometría, atributos y mediciones.",
    kmlDesc              = "Compatible con Google Earth y visores GIS básicos.",
    gpxDesc              = "Ideal para rutas, tracks y puntos GPS.",
    shpDesc              = "Genera puntos, líneas y polígonos como .shp/.shx/.dbf/.prj dentro de un ZIP.",
    sinEntidadesExportar = "Sin entidades para exportar.",
    herramientasTerreno  = "Herramientas de Terreno",
    corteManual          = "Corte Manual",
    trazarVia            = "Trazar Vía",
    subdividirLote       = "Subdividir Lote",
    trazarDireccionCorte = "Trazar dirección de corte",
    corte                = "Corte",
    subdividir           = "Subdividir",
    relleno              = "Relleno",
    borde                = "Borde",
    aplicarSubdivision   = "Aplicar subdivisión",
    subdivision          = "Subdivisión",
    frenteObjetivo       = "Frente objetivo",
    porArea              = "Por Área",
    partesIguales        = "Partes Iguales",
    frenteM              = "Frente (m)",
    areaPorParcela       = "Área por parcela (ha)",
    numeroParcelas       = "Número de parcelas",
    sinPoligono          = "Sin polígono",
    areaToggle           = "Área",
    ladosToggle          = "Lados",
    deshacerPunto        = "Deshacer punto",
    anadirPunto          = "Añadir punto",
    cortarDeNuevo        = "Cortar de nuevo:",
    tipoPlaceholder      = "Tipo…",
    trazarEje            = "Trazar eje →",
    dibujarEje           = "Dibujar eje →",
    editarParcelas       = "Editar parcelas",
    via                  = "Vía",
    seleccionarPoligono  = "Seleccionar polígono",
    sinPoligonosProyecto = "No hay polígonos en el proyecto activo.",
    poligonoNumero       = "Polígono #%d",
    parcelaDefault       = "Parcela",
    unidadesDistancia    = "Unidades de distancia",
    metros               = "Metros (m)",
    kilometros           = "Kilómetros (km)",
    unidadesArea         = "Unidades de área",
    idiomaLabel          = "Idioma",
    coordenadasLabel     = "Coordenadas",
    formatoGms           = "GMS  37°25'19\"N",
    temaLabel            = "Tema",
    oscuro               = "Oscuro",
    claro                = "Claro",
    mejorasComentarios   = "Mejoras y comentarios",
    feedbackDescripcion  = "¿Tienes sugerencias o encontraste un problema? Contáctanos por WhatsApp.",
    whatsappMensaje      = "Hola, tengo una sugerencia o comentario sobre GeoKepler:",
    escribirWhatsapp     = "Escribir por WhatsApp",
    dispositivoRootTitulo = "Dispositivo con permisos root",
    dispositivoRootDesc   = "Se detectaron permisos root en este dispositivo. GeoKepler puede continuar, pero los datos no están garantizados como seguros en este entorno.",
    entendido             = "Entendido",
    basemapSatelite      = "Satélite",
    basemapHibrido       = "Híbrido",
    basemapCalles        = "Calles",
    mapaDeFondo          = "Mapa de fondo",
    definirAreaDescarga  = "Definir área de descarga…",
    descargarAreaDefinida = "Descargar área definida",
    fuenteLabel          = "Fuente: %s",
    nivelDetalleMax      = "Nivel máximo de detalle: ",
    zoomBarrios          = "Barrios (resolución ~10m)",
    zoomCalles           = "Calles (~5m)",
    zoomManzanas         = "Manzanas (~3m)",
    zoomEdificios        = "Edificios (~1.5m)",
    zoomDetalleAlto      = "Detalle alto (~0.7m)",
    zoomMaximo           = "Máximo (~0.3m)",
    estimadoTiles        = "Estimado: %s (z14–z%d)",
    areaGrandeAdvertencia = "El área es grande — la descarga puede tardar varios minutos.",
    descargadoPct        = "%d%% descargado…",
    descargaCompletada   = "¡Descarga completada!",
    errorDescarga        = "Error en la descarga. Verifique la conexión de datos.",
    descargarBtn         = "Descargar",
    miUbicacion          = "Mi ubicación",
    continuarBtn         = "Continuar",
    editando             = "Editando: %s",
    cancelarEdicion      = "Cancelar edición",
    tocaMapaVertices     = "Toca el mapa para añadir vértices (%d/3 mínimo)",
    poligonoListo        = "Polígono listo (%d vértices) — confirma para continuar",
    gnssExterno          = "GNSS Externo",
    conectadoA           = "Conectado: %s",
    conectando           = "Conectando…",
    errorConDetalle      = "Error: %s",
    desconectado         = "Desconectado",
    desconectar          = "Desconectar",
    sinReceptoresBt      = "No hay receptores emparejados.\nVe a Ajustes → Bluetooth y empareja el receptor primero.",
    seleccionaReceptor   = "Selecciona el receptor:",
    dispositivoGenerico  = "Dispositivo",
    actualizarLista      = "Actualizar lista",
    detenerGrabacion     = "Detener grabación",
    grabarNmea           = "Grabar NMEA",
    compartirArchivoLbl  = "Compartir  %s",
    limpiarError         = "Limpiar error",
    ipReceptor           = "IP del receptor",
    puertoTcp            = "Puerto TCP",
    conectarWifiPrimero  = "Conéctese al WiFi del receptor antes de conectar",
    conectarBtn          = "Conectar",
    estadoLabel          = "Estado",
    idleLabel            = "Idle",
    conectadoLabel       = "Conectado",
    errorLabel           = "Error",
    grabacionLabel       = "Grabación",
    sinGrabacionActiva   = "Sin grabación activa",
    archivoActualLbl     = "ARCHIVO ACTUAL",
    carpetaActivaLbl     = "CARPETA ACTIVA",
    rutaGuardadoLbl      = "RUTA DE GUARDADO",
    ipHostLabel          = "IP / Host",
    puertoLabel          = "Puerto",
    usuarioLabel         = "Usuario",
    contrasenaLabel      = "Contraseña (%d caracteres)",
    mountpointLabel      = "Mountpoint",
    configuracionCompleta = "Configuración",
    velocidadLabel       = "VELOCIDAD",
    recibidosLabel       = "RECIBIDOS",
)

val StringsEn = AppStrings(
    proyectos     = "Projects",
    capas         = "Layers",
    basemap       = "Basemap",
    importar      = "Import",
    exportar      = "Export",
    parcelacion   = "Parceling",
    configuracion = "Settings",
    campoActivo   = "Active",
    menuLabel     = "Menu",
    gps           = "GPS",
    mapa          = "Map",
    finalizar     = "Done",
    cancelar      = "Cancel",
    deshacer      = "Undo",
    puntoGps      = "GPS Point",
    tocaMapaGps   = "Tap map or GPS",
    linea         = "Line",
    poligono      = "Polygon",
    punto         = "Point",
    herramientaCaptura = "CAPTURE TOOL",
    colapsar      = "Collapse",
    expandir      = "Expand",
    capasTitle    = "Layers",
    puntos        = "Points",
    lineas        = "Lines",
    poligonos     = "Polygons",
    sinEntidades  = "No captured entities.",
    entidades     = "entities",
    entidad       = "entity",
    rasteres      = "Rasters",
    eliminarTodoTitulo       = "Delete everything?",
    eliminarTodoConfirmacion = "%d entities will be deleted. This action cannot be undone.",
    eliminarTodoBoton        = "Delete all",
    nombreLabel              = "Name",
    propietarioLabel         = "Owner",
    propietarioAtributoLabel = "Owner / Attribute",
    norte         = "N",
    sur           = "S",
    este          = "E",
    oeste         = "W",
    nuevoProyecto = "New Project",
    sinProyectos  = "No projects. Tap + to create one.",
    sinNombre     = "No name",
    nombreProyectoLabel = "Project name",
    descripcionOpcional = "Description (optional)",
    crearProyecto        = "Create project",
    nuevo                = "New",
    descartar            = "Discard",
    guardar       = "Save",
    eliminar      = "Delete",
    editar        = "Edit",
    compartir     = "Share",
    sinGps        = "No GPS",
    volver        = "Back",
    ok            = "OK",
    confirmar     = "Confirm",
    cerrar        = "Close",
    ingresarCoord = "Enter coordinates",
    ingresarCoordGms = "Enter DMS coordinates",
    valoresInvalidos = "Invalid values",
    latitud       = "Latitude",
    longitud      = "Longitude",
    capturar      = "Capture",
    coordInvalidas= "Invalid coordinates",
    importarMapa         = "Import map",
    importarGeoPdf       = "Import GeoPDF / TIFF",
    importarKml          = "Import KML",
    importarGpx          = "Import GPX",
    importarGeoJson      = "Import GeoJSON",
    importarShapefile    = "Import Shapefile ZIP",
    ingresarCoordsManual = "Enter coordinates manually",
    rellenoPoligonos     = "Polygon fill",
    rellenoPoligonosDesc = "Show polygons with translucent background.",
    exportarDatos        = "Export data",
    geoJsonDesc          = "Recommended: preserves geometry, attributes and measurements.",
    kmlDesc              = "Compatible with Google Earth and basic GIS viewers.",
    gpxDesc              = "Ideal for routes, tracks and GPS points.",
    shpDesc              = "Generates points, lines and polygons as .shp/.shx/.dbf/.prj inside a ZIP.",
    sinEntidadesExportar = "No entities to export.",
    herramientasTerreno  = "Field Tools",
    corteManual          = "Manual Cut",
    trazarVia            = "Trace Road",
    subdividirLote       = "Subdivide Plot",
    trazarDireccionCorte = "Trace cut direction",
    corte                = "Cut",
    subdividir           = "Subdivide",
    relleno              = "Fill",
    borde                = "Border",
    aplicarSubdivision   = "Apply subdivision",
    subdivision          = "Subdivision",
    frenteObjetivo       = "Target frontage",
    porArea              = "By Area",
    partesIguales        = "Equal Parts",
    frenteM              = "Frontage (m)",
    areaPorParcela       = "Area per plot (ha)",
    numeroParcelas       = "Number of plots",
    sinPoligono          = "No polygon",
    areaToggle           = "Area",
    ladosToggle          = "Sides",
    deshacerPunto        = "Undo point",
    anadirPunto          = "Add point",
    cortarDeNuevo        = "Cut again:",
    tipoPlaceholder      = "Type…",
    trazarEje            = "Trace axis →",
    dibujarEje           = "Draw axis →",
    editarParcelas       = "Edit plots",
    via                  = "Road",
    seleccionarPoligono  = "Select polygon",
    sinPoligonosProyecto = "No polygons in the active project.",
    poligonoNumero       = "Polygon #%d",
    parcelaDefault       = "Plot",
    unidadesDistancia    = "Distance units",
    metros               = "Meters (m)",
    kilometros           = "Kilometers (km)",
    unidadesArea         = "Area units",
    idiomaLabel          = "Language",
    coordenadasLabel     = "Coordinates",
    formatoGms           = "DMS  37°25'19\"N",
    temaLabel            = "Theme",
    oscuro               = "Dark",
    claro                = "Light",
    mejorasComentarios   = "Feedback and suggestions",
    feedbackDescripcion  = "Have suggestions or found an issue? Contact us on WhatsApp.",
    whatsappMensaje      = "Hi, I have a suggestion or comment about GeoKepler:",
    escribirWhatsapp     = "Message us on WhatsApp",
    dispositivoRootTitulo = "Rooted device detected",
    dispositivoRootDesc   = "Root access was detected on this device. GeoKepler can continue, but data safety is not guaranteed in this environment.",
    entendido             = "Understood",
    basemapSatelite      = "Satellite",
    basemapHibrido       = "Hybrid",
    basemapCalles        = "Streets",
    mapaDeFondo          = "Background map",
    definirAreaDescarga  = "Define download area…",
    descargarAreaDefinida = "Download defined area",
    fuenteLabel          = "Source: %s",
    nivelDetalleMax      = "Maximum detail level: ",
    zoomBarrios          = "Neighborhoods (~10m resolution)",
    zoomCalles           = "Streets (~5m)",
    zoomManzanas         = "Blocks (~3m)",
    zoomEdificios        = "Buildings (~1.5m)",
    zoomDetalleAlto      = "High detail (~0.7m)",
    zoomMaximo           = "Maximum (~0.3m)",
    estimadoTiles        = "Estimated: %s (z14–z%d)",
    areaGrandeAdvertencia = "The area is large — the download may take several minutes.",
    descargadoPct        = "%d%% downloaded…",
    descargaCompletada   = "Download complete!",
    errorDescarga        = "Download error. Please check your data connection.",
    descargarBtn         = "Download",
    miUbicacion          = "My location",
    continuarBtn         = "Continue",
    editando             = "Editing: %s",
    cancelarEdicion      = "Cancel editing",
    tocaMapaVertices     = "Tap the map to add vertices (%d/3 minimum)",
    poligonoListo        = "Polygon ready (%d vertices) — confirm to continue",
    gnssExterno          = "External GNSS",
    conectadoA           = "Connected: %s",
    conectando           = "Connecting…",
    errorConDetalle      = "Error: %s",
    desconectado         = "Disconnected",
    desconectar          = "Disconnect",
    sinReceptoresBt      = "No paired receivers.\nGo to Settings → Bluetooth and pair the receiver first.",
    seleccionaReceptor   = "Select the receiver:",
    dispositivoGenerico  = "Device",
    actualizarLista      = "Refresh list",
    detenerGrabacion     = "Stop recording",
    grabarNmea           = "Record NMEA",
    compartirArchivoLbl  = "Share  %s",
    limpiarError         = "Clear error",
    ipReceptor           = "Receiver IP",
    puertoTcp            = "TCP Port",
    conectarWifiPrimero  = "Connect to the receiver's WiFi before connecting",
    conectarBtn          = "Connect",
    estadoLabel          = "Status",
    idleLabel            = "Idle",
    conectadoLabel       = "Connected",
    errorLabel           = "Error",
    grabacionLabel       = "Recording",
    sinGrabacionActiva   = "No active recording",
    archivoActualLbl     = "CURRENT FILE",
    carpetaActivaLbl     = "ACTIVE FOLDER",
    rutaGuardadoLbl      = "SAVE PATH",
    ipHostLabel          = "IP / Host",
    puertoLabel          = "Port",
    usuarioLabel         = "Username",
    contrasenaLabel      = "Password (%d characters)",
    mountpointLabel      = "Mountpoint",
    configuracionCompleta = "Settings",
    velocidadLabel       = "SPEED",
    recibidosLabel       = "RECEIVED",
)

fun stringsFor(lang: AppLanguage) = if (lang == AppLanguage.ENGLISH) StringsEn else StringsEs

val LocalStrings = compositionLocalOf<AppStrings> { StringsEs }
