package com.act.geomapper.ui.theme

import androidx.compose.runtime.compositionLocalOf
import com.act.geomapper.data.settings.AppLanguage

data class AppStrings(
    // Header
    val proyectos    : String,
    val capas        : String,
    val basemap      : String,
    val importar     : String,
    val exportar     : String,
    val parcelacion  : String,
    val configuracion: String,
    val campoActivo  : String,
    // Captura
    val gps          : String,
    val mapa         : String,
    val finalizar    : String,
    val cancelar     : String,
    val deshacer     : String,
    val puntoGps     : String,
    val tocaMapaGps  : String,
    val linea        : String,
    val poligono     : String,
    val punto        : String,
    // Capas
    val capasTitle   : String,
    val puntos       : String,
    val lineas       : String,
    val poligonos    : String,
    val sinEntidades : String,
    val entidades    : String,
    val entidad      : String,
    // Brújula
    val norte        : String,
    val sur          : String,
    val este         : String,
    val oeste        : String,
    // Proyectos
    val nuevoProyecto: String,
    val sinProyectos : String,
    val sinNombre    : String,
    // Acciones
    val guardar      : String,
    val eliminar      : String,
    val editar       : String,
    val compartir    : String,
    val sinGps       : String,
    // Coordenadas
    val ingresarCoord: String,
    val latitud      : String,
    val longitud     : String,
    val capturar     : String,
    val coordInvalidas: String,
    // Import
    val importarMapa         : String,
    val importarGeoPdf       : String,
    val importarKml          : String,
    val importarGpx          : String,
    val importarGeoJson      : String,
    val importarShapefile    : String,
    val ingresarCoordsManual : String,
    val rellenoPoligonos     : String,
    val rellenoPoligonosDesc : String,
    // Export
    val exportarDatos        : String,
    val geoJsonDesc          : String,
    val kmlDesc              : String,
    val gpxDesc              : String,
    val shpDesc              : String,
    val sinEntidadesExportar : String,
    // Parcelación
    val herramientasTerreno  : String,
    val corteManual          : String,
    val trazarVia            : String,
    val subdividirLote       : String,
    val trazarDireccionCorte : String,
    val corte                : String,
    val subdividir           : String,
    val relleno              : String,
    val borde                : String,
    val aplicarSubdivision   : String,
    val subdivision          : String,
    val frenteObjetivo       : String,
    val porArea              : String,
    val partesIguales        : String,
    val frenteM              : String,
    val areaPorParcela       : String,
    val numeroParcelas       : String,
)

val StringsEs = AppStrings(
    proyectos     = "Proyectos",
    capas         = "Capas",
    basemap       = "Mapa Base",
    importar      = "Importar",
    exportar      = "Exportar",
    parcelacion   = "Parcelación",
    configuracion = "Config.",
    campoActivo   = "Activo",
    gps           = "GPS",
    mapa          = "Mapa",
    finalizar     = "Fin",
    cancelar      = "Cancelar",
    deshacer      = "Deshacer",
    puntoGps      = "Punto GPS",
    tocaMapaGps   = "Toca el mapa o GPS",
    linea         = "Línea",
    poligono      = "Polígono",
    punto         = "Punto",
    capasTitle    = "Capas",
    puntos        = "Puntos",
    lineas        = "Líneas",
    poligonos     = "Polígonos",
    sinEntidades  = "Sin entidades capturadas.",
    entidades     = "entidades",
    entidad       = "entidad",
    norte         = "N",
    sur           = "S",
    este          = "E",
    oeste         = "O",
    nuevoProyecto = "Nuevo Proyecto",
    sinProyectos  = "Sin proyectos. Toca + para crear uno.",
    sinNombre     = "Sin nombre",
    guardar       = "Guardar",
    eliminar      = "Eliminar",
    editar        = "Editar",
    compartir     = "Compartir",
    sinGps        = "Sin GPS",
    ingresarCoord = "Ingresar coordenadas",
    latitud       = "Latitud",
    longitud      = "Longitud",
    capturar      = "Capturar",
    coordInvalidas= "Coordenadas inválidas",
    importarMapa         = "Importar mapa",
    importarGeoPdf       = "Importar GeoPDF / TIFF",
    importarKml          = "Importar KML",
    importarGpx          = "Importar GPX",
    importarGeoJson      = "Importar GeoJSON",
    importarShapefile    = "Importar Shapefile ZIP",
    ingresarCoordsManual = "Ingresar coordenadas manualmente",
    rellenoPoligonos     = "Relleno de polígonos",
    rellenoPoligonosDesc = "Ver polígonos con fondo translúcido.",
    exportarDatos        = "Exportar datos",
    geoJsonDesc          = "Recomendado: conserva geometría, atributos y mediciones.",
    kmlDesc              = "Compatible con Google Earth y visores GIS básicos.",
    gpxDesc              = "Ideal para rutas, tracks y puntos GPS.",
    shpDesc              = "Genera puntos, líneas y polígonos como .shp/.shx/.dbf/.prj dentro de un ZIP.",
    sinEntidadesExportar = "Sin entidades para exportar.",
    herramientasTerreno  = "Herramientas de Terreno",
    corteManual          = "Corte Manual",
    trazarVia            = "Trazar Vía",
    subdividirLote       = "Subdividir Lote",
    trazarDireccionCorte = "Trazar dirección de corte",
    corte                = "Corte",
    subdividir           = "Subdividir",
    relleno              = "Relleno",
    borde                = "Borde",
    aplicarSubdivision   = "Aplicar subdivisión",
    subdivision          = "Subdivisión",
    frenteObjetivo       = "Frente objetivo",
    porArea              = "Por Área",
    partesIguales        = "Partes Iguales",
    frenteM              = "Frente (m)",
    areaPorParcela       = "Área por parcela (ha)",
    numeroParcelas       = "Número de parcelas",
)

val StringsEn = AppStrings(
    proyectos     = "Projects",
    capas         = "Layers",
    basemap       = "Basemap",
    importar      = "Import",
    exportar      = "Export",
    parcelacion   = "Parceling",
    configuracion = "Settings",
    campoActivo   = "Active",
    gps           = "GPS",
    mapa          = "Map",
    finalizar     = "Done",
    cancelar      = "Cancel",
    deshacer      = "Undo",
    puntoGps      = "GPS Point",
    tocaMapaGps   = "Tap map or GPS",
    linea         = "Line",
    poligono      = "Polygon",
    punto         = "Point",
    capasTitle    = "Layers",
    puntos        = "Points",
    lineas        = "Lines",
    poligonos     = "Polygons",
    sinEntidades  = "No captured entities.",
    entidades     = "entities",
    entidad       = "entity",
    norte         = "N",
    sur           = "S",
    este          = "E",
    oeste         = "W",
    nuevoProyecto = "New Project",
    sinProyectos  = "No projects. Tap + to create one.",
    sinNombre     = "No name",
    guardar       = "Save",
    eliminar      = "Delete",
    editar        = "Edit",
    compartir     = "Share",
    sinGps        = "No GPS",
    ingresarCoord = "Enter coordinates",
    latitud       = "Latitude",
    longitud      = "Longitude",
    capturar      = "Capture",
    coordInvalidas= "Invalid coordinates",
    importarMapa         = "Import map",
    importarGeoPdf       = "Import GeoPDF / TIFF",
    importarKml          = "Import KML",
    importarGpx          = "Import GPX",
    importarGeoJson      = "Import GeoJSON",
    importarShapefile    = "Import Shapefile ZIP",
    ingresarCoordsManual = "Enter coordinates manually",
    rellenoPoligonos     = "Polygon fill",
    rellenoPoligonosDesc = "Show polygons with translucent background.",
    exportarDatos        = "Export data",
    geoJsonDesc          = "Recommended: preserves geometry, attributes and measurements.",
    kmlDesc              = "Compatible with Google Earth and basic GIS viewers.",
    gpxDesc              = "Ideal for routes, tracks and GPS points.",
    shpDesc              = "Generates points, lines and polygons as .shp/.shx/.dbf/.prj inside a ZIP.",
    sinEntidadesExportar = "No entities to export.",
    herramientasTerreno  = "Field Tools",
    corteManual          = "Manual Cut",
    trazarVia            = "Trace Road",
    subdividirLote       = "Subdivide Plot",
    trazarDireccionCorte = "Trace cut direction",
    corte                = "Cut",
    subdividir           = "Subdivide",
    relleno              = "Fill",
    borde                = "Border",
    aplicarSubdivision   = "Apply subdivision",
    subdivision          = "Subdivision",
    frenteObjetivo       = "Target frontage",
    porArea              = "By Area",
    partesIguales        = "Equal Parts",
    frenteM              = "Frontage (m)",
    areaPorParcela       = "Area per plot (ha)",
    numeroParcelas       = "Number of plots",
)

fun stringsFor(lang: AppLanguage) = if (lang == AppLanguage.ENGLISH) StringsEn else StringsEs

val LocalStrings = compositionLocalOf<AppStrings> { StringsEs }
